blueprint:
  name: Automatic air conditioner for summer, monitoring presence, window status, water level, time slot and external temperature sensor.
  description:  "`- Version: 1.3 -`\n\n This blueprint is for using the air conditioner automatically in the summer, based on a start and end temperature. 

          Optionally, you can enable:

          - External temperature sensor

          - Window status check
          
          - Water level control in the tank
          
          - Home presence control
          
          - Notifications
          
          - Decide on the time slot for operation"

  domain: automation
  input:

    climate:
      name: Entity climate
      description: 'Select climate entity to be used.'
      selector:
        entity:
          filter:
            domain: climate
          multiple: false

    temperature:
      name: Entity temperature sensor
      description: 'Select external temperature sensor entity to be used.'
      selector:
        entity:
          filter:
            domain: sensor
            device_class: temperature
          multiple: false

    set_temperature_climate:
      name: Set temperature climate
      default: 25
      description: 'Select the temperature to be set at climate.'
      selector:
        number:
          min: 20
          max: 30
          unit_of_measurement: 째C
          mode: slider
          step: 0.1

    hvac_modes:
      name: Hvac modes
      description: 'Select the mode to be set to the air conditioner.'
      default: cool
      selector:
        select:
          mode: dropdown
          options:
            - cool
            - dry
            - fan_only

    fan_modes:
      name: Fan modes
      description: 'Select the ventilation speed to be set at the air conditioner.'
      default: auto
      selector:
        select:
          mode: dropdown
          options:
            - auto
            - high
            - low
            - mid

    presence_home:
      name: Presence Home
      description: 'Select the group consisting of person..'
      default: group.presence_home_disabled
      selector:
        entity:
          domain: group

    moisture:
      name: Water level
      default: binary_sensor.moisture_disabled
      description: 'Select the binary_sensor used to measure the state of the water container. '
      selector:
        entity:
          domain: binary_sensor
          device_class: moisture

    window:
      name: Window
      default: binary_sensor.window_disabled
      description: 'Select the binary_sensor used for the window.'
      selector:
        entity:
          domain: binary_sensor
          device_class: window

    target_temperature_start:
      name: Target temperature start
      default: 25
      description: 'Set the startup target temperature.'
      selector:
        number:
          min: 20
          max: 30
          unit_of_measurement: 째C
          mode: slider
          step: 0.1

    target_temperature_stop:
      name: Target temperature stop
      default: 21
      description: 'Set the target temperature for shutdown.'
      selector:
        number:
          min: 20
          max: 30
          unit_of_measurement: 째C
          mode: slider
          step: 0.1

    delay_temperature_stop:
      default: 10
      name: Delay temperature stop
      description: 'Set the climate shutdown delay since the target temperature has been reached.'
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: min
          mode: slider
          step: 1

    start_time:
      name: Start time
      default: "00:00:00"
      description: 'Set automatic operation start time.'
      selector:
        time: 

    stop_time:
      name: Stop time
      default: "00:00:00"
      description: 'Set automatic operation end time.'
      selector:
        time: 

    notify_device:
      name: Device to notify push
      default: false
      description: 'Device needs to run the official Home Assistant app to receive notifications.'
      selector:
        device: 
          integration: mobile_app

mode: parallel
variables:
  target_temperature_start: !input target_temperature_start
  climate: !input climate
  temperature: !input temperature
  target_temperature_stop: !input target_temperature_stop
  window: !input window
  presence_home: !input presence_home
trigger:
- platform: state
  entity_id: !input moisture
  from: 'off'
  to: 'on'
  id: moisture_notify
- platform: state
  entity_id: !input moisture
  from: 'off'
  to: 'on'
  for:
    minutes: 5
  id: moisture_climate_off
- platform: numeric_state
  entity_id: !input temperature
  attribute: temperature
  above: !input target_temperature_start
  id: climate_on
- platform: numeric_state 
  entity_id: !input temperature
  attribute: temperature
  below: !input target_temperature_start
  id: climate_on
- platform: numeric_state
  entity_id: !input temperature
  attribute: temperature
  below: !input target_temperature_stop
  for: 
    minutes: !input delay_temperature_stop
  id: climate_off
- platform: numeric_state
  entity_id: !input temperature
  attribute: temperature
  above: !input target_temperature_stop
  for: 
    minutes: !input delay_temperature_stop
  id: climate_off
- platform: time
  at: !input stop_time
  id: climate_off
- platform: time
  at: !input start_time
  id: climate_on
- platform: state
  entity_id: !input window
  for:
    seconds: 60
  id: window
- platform: state
  entity_id: !input presence_home
  from: 
      - not_home
      - home
  to: 
      - not_home
      - home
  id: presence_home
action:
- alias: Full tank warning
  if: 
    - "{{ trigger.id == 'moisture_notify' and not is_state(climate,'off')}}"
  then: 
    - domain: mobile_app
      type: notify
      device_id: !input notify_device
      title: "Klima"
      message: "Klima ma plnu bandasku, automaticky sa vypne za 5 minut."
- alias: Turn air conditioner on
  if:
    - "{{is_state(climate,'off')}}"
    - condition: time
      after: !input start_time
      before: !input stop_time
    - "{{ states(presence_home) == 'home' or presence_home == 'group.presence_home_disabled'}}"
    - or: 
      - "{{ (trigger.id == 'climate_on' or trigger.id == 'window'or (trigger.id == 'presence_home' and trigger.to_state.state == 'home')) and (state_attr('sensor.temp_7_obyvka_battery','temperature')|float(1)) > target_temperature_start|float(1) )}}"
  then:
      - alias: Window control
        if: 
          - " {{ window == 'binary_sensor.window_disabled' or states(window) == 'off'}}"
        then: 
          - service: climate.set_temperature
            data:
              entity_id: !input climate
              temperature: !input set_temperature_climate
              hvac_mode: !input hvac_modes
          - delay: 
              seconds: 1
          - service: climate.set_fan_mode
            data:
              entity_id: !input climate
              fan_mode: !input fan_modes
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "Klima"
            message: "Klima pustena, je {{state_attr('sensor.temp_7_obyvka_battery','temperature')|float(1)}}째"
        else:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "Klima"
            message: "Klima sa nepustila, je otvorene okno."
- alias: Turn air conditioner off
  if: 
    - "{{not is_state(climate,'off')}}"
    - or: 
      - "{{ trigger.id == 'presence_home' and trigger.to_state.state == 'not_home'}}"
      - "{{ trigger.id == 'climate_off' and (state_attr('sensor.temp_7_obyvka_battery','temperature')|float(1)) < target_temperature_stop|float(1) )}}"
      - "{{ trigger.id == 'climate_off' and trigger.platform == 'time'}}"
      - "{{ trigger.id == 'window' and is_state(window,'on')}}"
      - "{{ trigger.id == 'moisture_climate_off' }}"
  then:
      - service: climate.turn_off
        target:
          entity_id: !input climate
      - domain: mobile_app
        type: notify
        device_id: !input notify_device
        title: "Klima"
        message: "{% if trigger.id == 'window' %} Klima sa vypla, lebo bolo otvorene okno.
                  {% elif (trigger.id == 'climate_off' or trigger.id == 'presence_home')%} Automaticke vypnutie klimy.
                  {% elif trigger.id == 'moisture_climate_off' %} Klima sa vypla, treba vyliat vodu.
                  {% endif %}"